### ISSUE TITLE
Feat: 아카이빙 11기 업데이트

### ISSUE THREAD

**Issue by cjy3458** [cau-likelion-org/cau-likelion-next#61]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 세션, 추억 탭 11기 업데이트

## TODO

- [ ] 11기 아카이빙 정보를 양식에 맞춰 보내주고 DB에 담기
- [ ] DB에 담겨있는 아카이빙 정보 렌더링
